# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en
title: Honor Native Land Fund
tagline: Honor Native Land Fund
email: HonorNativeLandFund@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Honor Native Land Fund (HNLF) is a voluntary monthly contribution or land tax that non-Native people living in the Midwest - 
  from the banks of the Mississippi to the Missouri - make to local Indigenous efforts to restore and rematriate 
  land and water to Indigenous stewardship.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.honornativelandfund.org" # the base hostname & protocol for your site, e.g. http://example.com
fixed_navbar: top
google_analytics: G-DN79M7TYGT

# Build settings
# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true
